[package]
name = "aws-lc-rs-api-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-lc-rs = { version = "1.0", path = "./aws-lc-rs/aws-lc-rs" }